import styles from './dashboard.module.css';
import type { Metadata } from "next";
import { Header } from "../components/sections/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (          
        <div className={styles.children_container}>
        <Header/>
        {children}
        </div>      
  );
}
